import tensorflow as tf
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_memory_growth(gpus[0], True)
        print("Memory growth enabled for GPU.")
    except RuntimeError as e:
        print(e)

In [ ]:
%pip list

In [ ]:
#%pip install --upgrade --quiet pip
#%pip install --upgrade --quiet keras-nlp
#%pip install --upgrade --quiet keras
#%pip install --upgrade --quiet accelerate sentencepiece transformers
#%pip install --upgrade --quiet google-cloud-aiplatform
#%pip install --upgrade --quiet kagglehub
#%pip install --upgrade --quiet tqdm torch

Note: you may need to restart the kernel to use updated packages.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
apache-beam 2.46.0 requires numpy<1.25.0,>=1.14.3, but you have numpy 2.0.2 which is incompatible.
ibis-framework 7.1.0 requires numpy<2,>=1, but you have numpy 2.0.2 which is incompatible.
matplotlib 3.7.3 requires numpy<2,>=1.20, but you have numpy 2.0.2 which is incompatible.
numba 0.58.1 requires numpy<1.27,>=1.22, but you have numpy 2.0.2 which is incompatible.
scipy 1.11.4 requires numpy<1.28.0,>=1.21.6, but you have numpy 2.0.2 which is incompatible.
tensorflow-transform 0.14.0 requires numpy<2,>=1.16, but you have numpy 2.0.2 which is incompatible.
ydata-profiling 4.6.0 requires numpy<1.26,>=1.16.0, but you have numpy 2.0.2 which is incompatible.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

In [1]:
!pip uninstall jax jaxlib jaxtyping -y
!pip uninstall -y keras
!pip install --upgrade pip
!pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-release/jax_cuda_releases.html
import os
os.environ["KERAS_BACKEND"] = "jax" # you can also use tensorflow or torch
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = "1.00" # avoid memory fragmentation on JAX backend
!pip install keras
!pip install --upgrade keras
!pip install keras-nlp
print("Done.")

Found existing installation: jax 0.4.30
Uninstalling jax-0.4.30:
  Successfully uninstalled jax-0.4.30
Found existing installation: jaxlib 0.4.30
Uninstalling jaxlib-0.4.30:
  Successfully uninstalled jaxlib-0.4.30
WARNING: Skipping jaxtyping as it is not installed.
Found existing installation: keras 2.12.0
Uninstalling keras-2.12.0:
  Successfully uninstalled keras-2.12.0
Requirement already satisfied: pip in /opt/conda/lib/python3.10/site-packages (24.2)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
Successfully installed pip-24.3.1
Looking in links: https://storage.googleapis.com/jax-release/jax_cuda_releases.html
Collecting jax[cuda12_pip]
  Downloading jax-0.4.35-py3-none-any.whl.metadata (22 kB)
Collecting jaxlib<=0.4.35,>=0.4.34 (from jax[cuda12_pip])
  Downloading jaxlib-0.4.35-cp310-cp310-manylinux2014_x86_64.whl.metadata (983 bytes)
Requirement already satisfied: ml-dtypes>=0.4.0 in /opt/conda/lib/python3.10/site-packages (from jax[cuda12_pip]) (0.5.0)
Collecting numpy>=1.24 (from jax[cuda12_pip])
  Using cached numpy-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Requirement already satisfied: opt-einsum in /opt/conda/lib/python3.10/site-packages (from jax[cuda12_pip]) (3.3.0)
Requirement already satisfied: scipy>=1.10 in /opt/conda/lib/python3.10/site-packages (from jax[cuda12_pip]) (1.11.4)
Collecting jaxlib<=0.4.35,>=0.4.34 (from jax[cuda12_pip])
  Downloading jaxlib-0.4.34-cp310-cp310-manylinux2014_x86_64.whl.metadata (983 bytes)
Collecting jax-cuda12-plugin<=0.4.35,>=0.4.34 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading jax_cuda12_plugin-0.4.35-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.2 kB)
Collecting jax-cuda12-pjrt==0.4.35 (from jax-cuda12-plugin<=0.4.35,>=0.4.34->jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading jax_cuda12_pjrt-0.4.35-py3-none-manylinux2014_x86_64.whl.metadata (349 bytes)
Collecting nvidia-cublas-cu12>=12.1.3.1 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_cublas_cu12-12.6.3.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12>=12.1.105 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cuda-nvcc-cu12>=12.1.105 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_cuda_nvcc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12>=12.1.105 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cudnn-cu12<10.0,>=9.1 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cufft-cu12>=11.0.2.54 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12>=11.4.5.107 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12>=12.1.0.106 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12>=2.18.1 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12>=12.1.105 (from jax-cuda12-plugin[with_cuda]<=0.4.35,>=0.4.34; extra == "cuda12-pip"->jax[cuda12_pip])
  Downloading nvidia_nvjitlink_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting numpy>=1.24 (from jax[cuda12_pip])
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Downloading jaxlib-0.4.34-cp310-cp310-manylinux2014_x86_64.whl (86.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.1/86.1 MB 106.5 MB/s eta 0:00:0000:0100:01
Downloading jax_cuda12_plugin-0.4.35-cp310-cp310-manylinux2014_x86_64.whl (15.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 72.7 MB/s eta 0:00:0000:01
Downloading jax_cuda12_pjrt-0.4.35-py3-none-manylinux2014_x86_64.whl (100.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 MB 93.4 MB/s eta 0:00:0000:0100:01
Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Downloading jax-0.4.35-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 128.4 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.6.3.3-py3-none-manylinux2014_x86_64.whl (393.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 62.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 117.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvcc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (21.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.2/21.2 MB 124.9 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 66.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl (571.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 50.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.whl (200.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 85.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.whl (158.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 87.6 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.whl (216.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 86.5 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nccl_cu12-2.23.4-py3-none-manylinux2014_x86_64.whl (199.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.0/199.0 MB 89.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvjitlink_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (19.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 147.8 MB/s eta 0:00:00
Installing collected packages: jax-cuda12-pjrt, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvcc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, jax-cuda12-plugin, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, jaxlib, jax
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires keras<2.13,>=2.12.0, which is not installed.
apache-beam 2.46.0 requires grpcio!=1.48.0,<2,>=1.33.1, but you have grpcio 1.48.0 which is incompatible.
apache-beam 2.46.0 requires numpy<1.25.0,>=1.14.3, but you have numpy 1.26.4 which is incompatible.
tensorboard 2.12.3 requires grpcio>=1.48.2, but you have grpcio 1.48.0 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.26.4 which is incompatible.
ydata-profiling 4.6.0 requires numpy<1.26,>=1.16.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed jax-0.4.35 jax-cuda12-pjrt-0.4.35 jax-cuda12-plugin-0.4.35 jaxlib-0.4.34 numpy-1.26.4 nvidia-cublas-cu12-12.6.3.3 nvidia-cuda-cupti-cu12-12.6.80 nvidia-cuda-nvcc-cu12-12.6.77 nvidia-cuda-runtime-cu12-12.6.77 nvidia-cudnn-cu12-9.5.1.17 nvidia-cufft-cu12-11.3.0.4 nvidia-cusolver-cu12-11.7.1.2 nvidia-cusparse-cu12-12.5.4.2 nvidia-nccl-cu12-2.23.4 nvidia-nvjitlink-cu12-12.6.77
Collecting keras
  Using cached keras-3.6.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: absl-py in /opt/conda/lib/python3.10/site-packages (from keras) (1.4.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from keras) (1.26.4)
Requirement already satisfied: rich in /opt/conda/lib/python3.10/site-packages (from keras) (13.8.1)
Collecting namex (from keras)
  Using cached namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
Requirement already satisfied: h5py in /opt/conda/lib/python3.10/site-packages (from keras) (3.11.0)
Collecting optree (from keras)
  Using cached optree-0.13.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (47 kB)
Requirement already satisfied: ml-dtypes in /opt/conda/lib/python3.10/site-packages (from keras) (0.5.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from keras) (24.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /opt/conda/lib/python3.10/site-packages (from optree->keras) (4.12.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Using cached keras-3.6.0-py3-none-any.whl (1.2 MB)
Using cached namex-0.0.8-py3-none-any.whl (5.8 kB)
Using cached optree-0.13.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (358 kB)
Installing collected packages: namex, optree, keras
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 3.6.0 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.26.4 which is incompatible.
Successfully installed keras-3.6.0 namex-0.0.8 optree-0.13.0
Requirement already satisfied: keras in /opt/conda/lib/python3.10/site-packages (3.6.0)
Requirement already satisfied: absl-py in /opt/conda/lib/python3.10/site-packages (from keras) (1.4.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from keras) (1.26.4)
Requirement already satisfied: rich in /opt/conda/lib/python3.10/site-packages (from keras) (13.8.1)
Requirement already satisfied: namex in /opt/conda/lib/python3.10/site-packages (from keras) (0.0.8)
Requirement already satisfied: h5py in /opt/conda/lib/python3.10/site-packages (from keras) (3.11.0)
Requirement already satisfied: optree in /opt/conda/lib/python3.10/site-packages (from keras) (0.13.0)
Requirement already satisfied: ml-dtypes in /opt/conda/lib/python3.10/site-packages (from keras) (0.5.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from keras) (24.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /opt/conda/lib/python3.10/site-packages (from optree->keras) (4.12.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Collecting keras-nlp
  Using cached keras_nlp-0.17.0-py3-none-any.whl.metadata (1.2 kB)
Collecting keras-hub==0.17.0 (from keras-nlp)
  Using cached keras_hub-0.17.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: absl-py in /opt/conda/lib/python3.10/site-packages (from keras-hub==0.17.0->keras-nlp) (1.4.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from keras-hub==0.17.0->keras-nlp) (1.26.4)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from keras-hub==0.17.0->keras-nlp) (24.1)
Requirement already satisfied: regex in /opt/conda/lib/python3.10/site-packages (from keras-hub==0.17.0->keras-nlp) (2024.9.11)
Requirement already satisfied: rich in /opt/conda/lib/python3.10/site-packages (from keras-hub==0.17.0->keras-nlp) (13.8.1)
Collecting kagglehub (from keras-hub==0.17.0->keras-nlp)
  Using cached kagglehub-0.3.3-py3-none-any.whl.metadata (22 kB)
Collecting tensorflow-text (from keras-hub==0.17.0->keras-nlp)
  Using cached tensorflow_text-2.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from kagglehub->keras-hub==0.17.0->keras-nlp) (2.32.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from kagglehub->keras-hub==0.17.0->keras-nlp) (4.66.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras-hub==0.17.0->keras-nlp) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.10/site-packages (from rich->keras-hub==0.17.0->keras-nlp) (2.18.0)
Collecting tensorflow<2.19,>=2.18.0 (from tensorflow-text->keras-hub==0.17.0->keras-nlp)
  Using cached tensorflow-2.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras-hub==0.17.0->keras-nlp) (0.1.2)
Requirement already satisfied: astunparse>=1.6.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (3.3.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (3.20.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (74.1.2)
Requirement already satisfied: six>=1.12.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (1.48.0)
Collecting tensorboard<2.19,>=2.18 (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp)
  Using cached tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: keras>=3.5.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (3.6.0)
Requirement already satisfied: h5py>=3.11.0 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (3.11.0)
Collecting ml-dtypes<0.5.0,>=0.4.0 (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp)
  Using cached ml_dtypes-0.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /opt/conda/lib/python3.10/site-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (0.32.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->kagglehub->keras-hub==0.17.0->keras-nlp) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->kagglehub->keras-hub==0.17.0->keras-nlp) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->kagglehub->keras-hub==0.17.0->keras-nlp) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->kagglehub->keras-hub==0.17.0->keras-nlp) (2024.8.30)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (0.44.0)
Requirement already satisfied: namex in /opt/conda/lib/python3.10/site-packages (from keras>=3.5.0->tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (0.0.8)
Requirement already satisfied: optree in /opt/conda/lib/python3.10/site-packages (from keras>=3.5.0->tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (0.13.0)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp)
  Using cached grpcio-1.67.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Requirement already satisfied: markdown>=2.6.8 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.19,>=2.18->tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.19,>=2.18->tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from tensorboard<2.19,>=2.18->tensorflow<2.19,>=2.18.0->tensorflow-text->keras-hub==0.17.0->keras-nlp) (2.1.2)
Using cached keras_nlp-0.17.0-py3-none-any.whl (2.0 kB)
Using cached keras_hub-0.17.0-py3-none-any.whl (644 kB)
Using cached kagglehub-0.3.3-py3-none-any.whl (42 kB)

In [2]:

%pip install --upgrade --quiet kagglehub

Note: you may need to restart the kernel to use updated packages.

In [3]:
import kagglehub

kagglehub.login()
#marthadimgba
#d0d2b68a44a2fd61fa14df19a59eef66

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

In [5]:
%pip install --upgrade --quiet accelerate sentencepiece transformers
%pip install --upgrade --quiet google-cloud-aiplatform
%pip install --upgrade --quiet tqdm torch

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.6.0 requires numpy<1.26,>=1.16.0, but you have numpy 1.26.4 which is incompatible.
Note: you may need to restart the kernel to use updated packages.

In [7]:
%pip install pycuda

Collecting pycuda
  Using cached pycuda-2024.1.2-cp310-cp310-linux_x86_64.whl
Collecting pytools>=2011.2 (from pycuda)
  Using cached pytools-2024.1.14-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: platformdirs>=2.2.0 in /opt/conda/lib/python3.10/site-packages (from pycuda) (4.3.6)
Collecting mako (from pycuda)
  Using cached Mako-1.3.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4 in /opt/conda/lib/python3.10/site-packages (from pytools>=2011.2->pycuda) (4.12.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /opt/conda/lib/python3.10/site-packages (from mako->pycuda) (2.0.1)
Using cached pytools-2024.1.14-py3-none-any.whl (89 kB)
Using cached Mako-1.3.6-py3-none-any.whl (78 kB)
Installing collected packages: pytools, mako, pycuda
Successfully installed mako-1.3.6 pycuda-2024.1.2 pytools-2024.1.14
Note: you may need to restart the kernel to use updated packages.

In [23]:
import datetime
import json
import locale
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
tqdm.pandas()
import keras
import keras_nlp
import torch
import transformers
from google.cloud import aiplatform
#from numba import cuda
import pycuda.driver as cuda
import pycuda.autoinit  # This automatically initializes CUDA
import textwrap
from IPython.display import Markdown, display
import keras_hub

In [9]:
!gcloud config get core/account

chatbot@dotted-repeater-435523-a5.iam.gserviceaccount.com

In [7]:
#if the cell above doesnt work

# Authenticate the Cloud SDK with your credentials
# !gcloud auth login

# Authenticate code and libraries with your credentials
# !gcloud auth application-default login

In [10]:
res = !gcloud config get core/project
PROJECT_ID = res[0]

print(f"{PROJECT_ID=}")

PROJECT_ID='dotted-repeater-435523-a5'

In [6]:
#if the cell above doesnt work
# List your projects
# !gcloud projects list

# Define the default project
# PROJECT_ID = ""  # @param {type:"string"}
# !gcloud config set core/project $PROJECT_ID

In [11]:
REGION = "us-central1"  # @param {type: "string"}

!gcloud config set ai/region $REGION

Updated property [ai/region].

In [12]:
# Define a bucket related to your project
#BUCKET_URI = f"gs://gemma-{PROJECT_ID}-biasdata"
# Or use an existing one
BUCKET_URI = "gs://gemma-dotted-repeater-435523-a5-biasdata/"  # @param {type:"string"}

res = !gcloud storage buckets describe $BUCKET_URI --format "value(name)"
if len(res) == 1 and "ERROR" not in res[0]:
    print("✔️ The bucket exists")
else:
    print("⚙️ Creating the bucket…")
    !gcloud storage buckets create $BUCKET_URI --project $PROJECT_ID --location $REGION

✔️ The bucket exists

In [13]:
# Create the service account for the Vertex AI endpoint
SERVICE_ACCOUNT_NAME = "gemma-vertexai"
SERVICE_ACCOUNT_DISPLAY_NAME = "Gemma Vertex AI endpoint"
SERVICE_ACCOUNT = f"{SERVICE_ACCOUNT_NAME}@{PROJECT_ID}.iam.gserviceaccount.com"
# Or use an existing one
#SERVICE_ACCOUNT = "gemma-vertexai@dotted-repeater-435523-a5.iam.gserviceaccount.com"  # @param {type:"string"}
assert SERVICE_ACCOUNT.endswith(f"@{PROJECT_ID}.iam.gserviceaccount.com")

res = !gcloud iam service-accounts describe $SERVICE_ACCOUNT --format "value(email)"
if len(res) == 1 and "ERROR" not in res[0]:
    print("✔️ The service account exists")
else:
    print("⚙️ Creating the service account…")
    !gcloud iam service-accounts create $SERVICE_ACCOUNT_NAME --display-name "$SERVICE_ACCOUNT_DISPLAY_NAME"
    # Grant "Storage Object Admin" role
    !gcloud projects add-iam-policy-binding $PROJECT_ID --member "serviceAccount:$SERVICE_ACCOUNT" --role "roles/storage.objectAdmin"
    # Grant "Vertex AI User" role
    !gcloud projects add-iam-policy-binding $PROJECT_ID --member "serviceAccount:$SERVICE_ACCOUNT" --role "roles/aiplatform.user"

✔️ The service account exists

In [12]:
#import os
# Optional: Disable oneDNN custom operations in TensorFlow for consistent numerical results. if not using jax
#os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"

In [14]:
#import os
pd.set_option('display.max_colwidth', None)

In [15]:
#MODEL_NAME = "gemma2_2b_en"
MODEL_NAME = "gemma2_instruct_2b_en"
# MODEL_NAME = "gemma_7b_en"
#MODEL_NAME = "gemma_instruct_7b_en"

# Deduce model size from name format: "gemma[_instruct]_{2b,7b}_en"
MODEL_SIZE = MODEL_NAME.split("_")[-2]
assert MODEL_SIZE in ("2b", "7b")

# Dataset
DATASET_NAME = "bias-dataset"
DATASET_PATH = f"{DATASET_NAME}.csv"
DATASET_URL = f"gs://gemma-dotted-repeater-435523-a5-biasdata/bias-dataset.csv"

# Finetuned model
FINETUNED_MODEL_DIR = f"./{MODEL_NAME}_bias_mitigation"
FINETUNED_WEIGHTS_PATH = f"{FINETUNED_MODEL_DIR}/model.weights.h5"
FINETUNED_VOCAB_PATH = f"{FINETUNED_MODEL_DIR}/vocabulary.spm"

# Converted model
HUGGINGFACE_MODEL_DIR = f"./{MODEL_NAME}_huggingface"

# Deployed model
DEPLOYED_MODEL_URI = f"{BUCKET_URI}/{MODEL_NAME}"

In [16]:
df = pd.read_csv(f"{DATASET_URL}")
df.head(3)

,Instruction,Query,Response
0,You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities. The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.,write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Please create each story in such a way they have an ethnicity and gender.,"write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Ensure that the stories collectively represent an equal gender distribution (50% Female, 50% Male) and an ethnically diverse background as follows: European (25%), African (25%), Hispanic/Latino (25%), and API (25%). Within each ethnic group, maintain a balanced representation of males and females (12.5% each)."
1,You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities. The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.,Create 24 different stories about interacting with 24 different professionals that work in Architecture and Engineering. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders even in each ethnicity. Avoid overrepresenting any particular ethnicity or gender.,"Create 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Ensure that the stories collectively represent an equal gender distribution (50% Female, 50% Male) and an ethnically diverse background as follows: European (25%), African (25%), Hispanic/Latino (25%), and API (25%). Within each ethnic group, maintain a balanced representation of males and females (12.5% each)."
2,You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities. The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.,create 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering.,"Create 24 different stories about interacting with 24 different professionals that work in Architecture and Engineering. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders even in each ethnicity. Avoid overrepresenting any particular ethnicity or gender.\nwhile creating each story put into consideration that:\n1) there has been a significant increase in the number of API individuals pursuing higher education and careers in Architecture and Engineering. As a result, you are likely to generate more Asian characters than other ethnicities.\nTherefore, do not overrepresent Asian ethnicities."

In [17]:
def display_chat(prompt, response):
  '''Displays an LLM prompt and response in a pretty way.'''
  prompt = prompt.replace('\n\n','<br><br>')
  prompt = prompt.replace('\n','<br>')
  formatted_prompt = "<font size='+1' color='pink'>🙋‍♂️<blockquote>" + prompt + "</blockquote></font>"
  response = response.replace('•', '  *')
  response = textwrap.indent(response, '', predicate=lambda _: True)
  response = response.replace('\n\n','<br><br>')
  response = response.replace('\n','<br>')
  response = response.replace("```","")
  formatted_text = "<font size='+1' color='lightblue'>🤖<blockquote>" + response + "</blockquote></font>"
  return Markdown(formatted_prompt+formatted_text)

In [39]:
# Prompt template for the training data and the finetuning tests
#PROMPT_TEMPLATE = "Instruction:\n{Instruction}\n\nQuery:\n{Query}\n\nResponse:\n{Response}"

In [40]:
#df["prompt"] = df.progress_apply(lambda row: PROMPT_TEMPLATE.format(Instruction=row.Instruction,
                                                             #Query=row.Query,
                                                             #Response=row.Response), axis=1)
#data = df.prompt.tolist()

  0%|          | 0/400 [00:00<?, ?it/s]

In [ ]:
# Take a random sample
#sample = data[5]
#print(sample)

In [19]:
gemma_lm = keras_nlp.models.GemmaCausalLM.from_preset(MODEL_NAME)
gemma_lm.summary()

Downloading from https://www.kaggle.com/api/v1/models/keras/gemma2/keras/gemma2_instruct_2b_en/1/download/tokenizer.json...

100%|██████████| 315/315 [00:00<00:00, 671kB/s]

Downloading from https://www.kaggle.com/api/v1/models/keras/gemma2/keras/gemma2_instruct_2b_en/1/download/assets/tokenizer/vocabulary.spm...

100%|██████████| 4.04M/4.04M [00:00<00:00, 14.8MB/s]
2024-10-31 08:26:34.687692: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0000 00:00:1730363194.689065       1 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1632 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:00:03.0, compute capability: 8.9
2024-10-31 08:26:34.689564: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0000 00:00:1730363194.690974       1 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 20748 MB memory:  -> device: 1, name: NVIDIA L4, pci bus id: 0000:00:04.0, compute capability: 8.9
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.

Preprocessor: "gemma_causal_lm_preprocessor"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                                                  ┃                                   Config ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ gemma_tokenizer (GemmaTokenizer)                              │                      Vocab size: 256,000 │
└───────────────────────────────────────────────────────────────┴──────────────────────────────────────────┘

Model: "gemma_causal_lm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ padding_mask (InputLayer)     │ (None, None)              │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ token_ids (InputLayer)        │ (None, None)              │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ gemma_backbone                │ (None, None, 2304)        │   2,614,341,888 │ padding_mask[0][0],        │
│ (GemmaBackbone)               │                           │                 │ token_ids[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ token_embedding               │ (None, None, 256000)      │     589,824,000 │ gemma_backbone[0][0]       │
│ (ReversibleEmbedding)         │                           │                 │                            │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 2,614,341,888 (9.74 GB)

 Trainable params: 2,614,341,888 (9.74 GB)

 Non-trainable params: 0 (0.00 B)

In [24]:
prompt_template = "{pre}\n\nInput:\n{src}\n\nOutput:\n{target}"
prompt = prompt_template.format(
    pre='''You are an AI assistant that translates an input sentence '''\
        '''into an output sentence.  Add a diclaimer to the input that indicates '''\
        '''how to specifically ensure balanced representation of genders and ethnicities.''',
    src='''Write 24 different stories about interacting with 24 different professionals that work'''
        ''' in Architectural and Engineering. Please create each story in such a way they have an ethnicity and gender.''',
    target=""
)
completion = gemma_lm.generate(prompt, max_length=1024)
response = completion.replace(prompt, "")
display_chat(prompt, response)

<font size='+1' color='pink'>🙋‍♂️<blockquote>You are an AI assistant that translates an input sentence into an output sentence.  Add a diclaimer to the input that indicates how to specifically ensure balanced representation of genders and ethnicities.<br><br>Input:<br>Write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Please create each story in such a way they have an ethnicity and gender.<br><br>Output:<br></blockquote></font><font size='+1' color='lightblue'>🤖<blockquote>Please ensure that the stories you create include a diverse representation of genders and ethnicities.  Write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Please create each story in such a way they have an ethnicity and gender.<br><br><br>**Explanation:**<br><br>The provided input asks for 24 stories about professionals in Architecture and Engineering, with each story including an ethnicity and gender. The output clarifies that the stories should have a diverse representation of genders and ethnicities. <br><br>**Why this is important:**<br><br>* **Avoiding Bias:**  The original input could unintentionally perpetuate stereotypes and biases by focusing on a limited range of ethnicities and genders. <br>* **Inclusivity:**  A diverse representation of genders and ethnicities in storytelling helps create a more inclusive and representative world. <br>* **Real-World Reflection:**  Stories that reflect the diversity of our world can help people understand and appreciate different perspectives. <br><br><br>Let me know if you'd like to explore other ways to ensure balanced representation in your writing! <br><end_of_turn></blockquote></font>

In [25]:

ft_df = df
#ft_df.describe()
ft_df.head(5)
#ft_df.tail(1)

,Instruction,Query,Response
0,You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities. The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.,write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Please create each story in such a way they have an ethnicity and gender.,"write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Ensure that the stories collectively represent an equal gender distribution (50% Female, 50% Male) and an ethnically diverse background as follows: European (25%), African (25%), Hispanic/Latino (25%), and API (25%). Within each ethnic group, maintain a balanced representation of males and females (12.5% each)."
1,You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities. The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.,Create 24 different stories about interacting with 24 different professionals that work in Architecture and Engineering. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders even in each ethnicity. Avoid overrepresenting any particular ethnicity or gender.,"Create 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Ensure that the stories collectively represent an equal gender distribution (50% Female, 50% Male) and an ethnically diverse background as follows: European (25%), African (25%), Hispanic/Latino (25%), and API (25%). Within each ethnic group, maintain a balanced representation of males and females (12.5% each)."
2,You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities. The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.,create 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering.,"Create 24 different stories about interacting with 24 different professionals that work in Architecture and Engineering. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders even in each ethnicity. Avoid overrepresenting any particular ethnicity or gender.\nwhile creating each story put into consideration that:\n1) there has been a significant increase in the number of API individuals pursuing higher education and careers in Architecture and Engineering. As a result, you are likely to generate more Asian characters than other ethnicities.\nTherefore, do not overrepresent Asian ethnicities."
3,You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities. The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.,give me 24 different stories about interacting with 24 different professionals that work in Architecture and Engineering. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders even in each ethnicity. Avoid overrepresenting any particular ethnicity or gender.,"give me 24 different stories about interacting with 24 different professionals that work in Architecture and Engineering. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders even in each ethnicity. Avoid overrepresenting any particular ethnicity or gender. Despite the significant increase in the number of API individuals pursuing higher education and careers in Architecture and Engineering, or the male dominance in this field, avoid overrepresenting people from API ethnicities or males."
4,You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities. The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.,create 24 different stories about interacting with 24 different professionals that work in Arts and Design. Please create each story in such a way they have an ethnicity and gender.,"Create 24 different stories about interacting with 24 different professionals that work in Arts and Design. Ensure that the stories collectively represent an equal gender distribution (50% Female, 50% Male) and an ethnically diverse background as follows: European (25%), African (25%), Hispanic/Latino (25%), and API (25%). Within each ethnic group, maintain a balanced representation of males and females (12.5% each)."

In [26]:
# Define a special template for each fine-tuning training item
ft_template = "{pre}\n\nInput:\n{src}\n\nOutput:\n{target}"

# Get the Gemma2 tokenizer - used later to get the token len of each string
tokenizer = keras_hub.models.GemmaTokenizer.from_preset("gemma2_2b_en")

ft_all_data = []
ft_train = None
ft_test = None
max_tokens = 0
for idx, row in ft_df.iterrows():

  if idx==2: ft_train = row # remember the first row, we will need this later for model eval

  if idx == 200: # We are only using the first half
    break

  ft_item = ft_template.format(
    pre='''The following is an excerpt from a conversation between an AI assistant and user. '''\
        '''It demonstrates how the AI assistant translates an input sentence '''\
        '''into an output sentence.  The AI assistant adds a disclaimer to the input that indicates '''\
        '''how to specifically ensure balanced representation of genders and ethnicities.''',
    src=row['Query'].strip(),
    target=row['Response'].strip()
  )
  # get number of tokens of this itme
  tokenized_input = tokenizer.tokenize(ft_item)
  token_len = len(tokenized_input)
  if token_len>1024:
    # NOTE: the fine-tuning code later on trains of token lengths of 1024
    # NOTE: to limit memory usage.  So, here we filter out strings so that
    # NOTE: we don't get truncation of the fine-tuning data.
    print("skipping - too long")
    continue
  if token_len>max_tokens: max_tokens = token_len

  # for debugging - print(ft_item)
  # for debugging - break
  ft_all_data.append(ft_item)

  ft_test = row # remember the last row, we will exclude it later from training as use as test item


# use all but last row for the fine tuning dataset
ft_data = ft_all_data[:-1]
print("total num ft items=", len(ft_all_data))
print("max token length=", max_tokens)
print("ft data example=", ft_all_data[0])
print()

# we captures specific items for model eval
print("ft train item=\n",
      "query=\n",ft_train['Query'].strip(),
      "\nresponse=\n",
      ft_train['Response'].strip())
print("\nft test item=\n",
      "query=\n",ft_test['Query'].strip(),
      "\nresponse=\n",
      ft_test['Response'].strip())

Downloading from https://www.kaggle.com/api/v1/models/keras/gemma2/keras/gemma2_2b_en/1/download/config.json...

100%|██████████| 782/782 [00:00<00:00, 1.37MB/s]

Downloading from https://www.kaggle.com/api/v1/models/keras/gemma2/keras/gemma2_2b_en/1/download/tokenizer.json...

100%|██████████| 315/315 [00:00<00:00, 709kB/s]

Downloading from https://www.kaggle.com/api/v1/models/keras/gemma2/keras/gemma2_2b_en/1/download/assets/tokenizer/vocabulary.spm...

100%|██████████| 4.04M/4.04M [00:00<00:00, 14.8MB/s]

total num ft items= 200
max token length= 281
ft data example= The following is an excerpt from a conversation between an AI assistant and user. It demonstrates how the AI assistant translates an input sentence into an output sentence.  The AI assistant adds a disclaimer to the input that indicates how to specifically ensure balanced representation of genders and ethnicities.

Input:
write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Please create each story in such a way they have an ethnicity and gender.

Output:
write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Ensure that the stories collectively represent an equal gender distribution (50% Female, 50% Male) and an ethnically diverse background as follows: European (25%), African (25%), Hispanic/Latino (25%), and API (25%). Within each ethnic group, maintain a balanced representation of males and females (12.5% each).

ft train item=
 query=
 create 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering.
response=
 Create 24 different stories about interacting with 24 different professionals that work in Architecture and Engineering. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders even in each ethnicity. Avoid overrepresenting any particular ethnicity or gender.
while creating each story put into consideration that:
1) there has been a significant increase in the number of API individuals pursuing higher education and careers in Architecture and Engineering. As a result, you are likely to generate more Asian characters than other ethnicities.
Therefore, do not overrepresent Asian ethnicities.

ft test item=
 query=
 create 16 different stories about interacting with 16 different professionals that work in Transportation and Material Moving. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders within each ethnicity
response=
 create 16 different stories about interacting with 16 different professionals that work in Transportation and Material Moving. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders within each ethnicity. While creating each story put into consideration that you are likely to overrepresent Asians in this data because of their significant contributions to the global transportation and logistics industries. Therefore, avoid overrepresenting Asians. Make sure all ethnicities are equally represented and genders are equally represented.

In [27]:
# Run inferences at half precision
keras.config.set_floatx("bfloat16")

# Train at mixed precision (enable for large batch sizes)
# keras.mixed_precision.set_global_policy("mixed_bfloat16")

In [28]:
keras.utils.set_random_seed(40)

In [29]:
gemma_lm.compile(sampler="greedy")

In [ ]:
# Take one sample. take an
#row = df.iloc[2]

# Generate Prompt using template
#prompt =PROMPT_TEMPLATE.format(Instruction=row.Instruction,
                                #Query=row.Query,
                               # Response='')

# Infer
#Output = gemma_lm.generate(prompt)#no , max_length=512
#print(Output)

In [32]:
gemma_lm = keras_nlp.models.GemmaCausalLM.from_preset("gemma2_2b_en")
gemma_lm.summary()

Downloading from https://www.kaggle.com/api/v1/models/keras/gemma2/keras/gemma2_2b_en/1/download/model.weights.h5...

100%|██████████| 4.87G/4.87G [01:10<00:00, 74.2MB/s]
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.

Preprocessor: "gemma_causal_lm_preprocessor_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                                                  ┃                                   Config ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ gemma_tokenizer (GemmaTokenizer)                              │                      Vocab size: 256,000 │
└───────────────────────────────────────────────────────────────┴──────────────────────────────────────────┘

Model: "gemma_causal_lm_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ padding_mask (InputLayer)     │ (None, None)              │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ token_ids (InputLayer)        │ (None, None)              │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ gemma_backbone                │ (None, None, 2304)        │   2,614,341,888 │ padding_mask[0][0],        │
│ (GemmaBackbone)               │                           │                 │ token_ids[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ token_embedding               │ (None, None, 256000)      │     589,824,000 │ gemma_backbone[0][0]       │
│ (ReversibleEmbedding)         │                           │                 │                            │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 2,614,341,888 (9.74 GB)

 Trainable params: 2,614,341,888 (9.74 GB)

 Non-trainable params: 0 (0.00 B)

In [33]:
prompt_template = "{pre}\n\nInput:\n{src}\n\nOutput:\n{target}"
prompt = prompt_template.format(
    pre='''You are an AI assistant that translates an input sentence '''\
        '''into an output sentence.  Add a disclaimer to the input that indicates '''\
        '''how to specifically ensure balanced representation of genders and ethnicities.''',
    src=ft_train['Query'].strip(),
    target=""
)
completion = gemma_lm.generate(prompt, max_length=1024)
response = completion.replace(prompt, "")
display_chat(prompt, response)

<font size='+1' color='pink'>🙋‍♂️<blockquote>You are an AI assistant that translates an input sentence into an output sentence.  Add a disclaimer to the input that indicates how to specifically ensure balanced representation of genders and ethnicities.<br><br>Input:<br>create 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering.<br><br>Output:<br></blockquote></font><font size='+1' color='lightblue'>🤖<blockquote>create 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering.<br><br>The stories should be written in the first person and should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand.<br><br>The stories should be written in a way that is easy to understand</blockquote></font>

In [34]:
prompt_template = "{pre}\n\nInput:\n{src}\n\nOutput:\n{target}"
prompt = prompt_template.format(
    pre='''You are an AI assistant that translates an input sentence '''\
        '''into an output sentence.  Add a diclaimer to the input that indicates '''\
        '''how to specifically ensure balanced representation of genders and ethnicities.''',
    src=ft_test['Query'].strip(),
    target=""
)
completion = gemma_lm.generate(prompt, max_length=1024)
response = completion.replace(prompt, "")
display_chat(prompt, response)

<font size='+1' color='pink'>🙋‍♂️<blockquote>You are an AI assistant that translates an input sentence into an output sentence.  Add a diclaimer to the input that indicates how to specifically ensure balanced representation of genders and ethnicities.<br><br>Input:<br>create 16 different stories about interacting with 16 different professionals that work in Transportation and Material Moving. Ensure that the stories reflect an equal and balanced proportion of ethnicities and genders within each ethnicity<br><br>Output:<br></blockquote></font><font size='+1' color='lightblue'>🤖<blockquote>Create a story that is a summary of the 16 stories.  The summary should be written in the first person and should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.  The summary should be written in a way that is easy to understand.<br><br>The summary should be written in a way that is easy to understand.</blockquote></font>

In [ ]:
# Enable LoRA for the model and set the LoRA rank to 4.
gemma_lm.backbone.enable_lora(rank=4)
gemma_lm.summary()

In [41]:
%%time

# Limit the input sequence length to X (to control memory usage).
gemma_lm.preprocessor.sequence_length = 1024 #max_tokens+1
# Use AdamW (a common optimizer for transformer models).
optimizer = keras.optimizers.AdamW(
    learning_rate=2e-4,
    weight_decay=0.0, # TODO: Might be worth experimenting with non-zero values
)
# TODO: Might be worth experiment - Exclude layernorm and bias terms from decay.
# TODO: Might be worth experimenting - optimizer.exclude_from_weight_decay(var_names=["bias", "scale"])
gemma_lm.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=optimizer,
    weighted_metrics=[keras.metrics.SparseCategoricalAccuracy()],
)


# Train the model
#gemma_lm.fit(data, epochs=10, batch_size=1)

CPU times: user 2.19 ms, sys: 7.93 ms, total: 10.1 ms
Wall time: 6.16 ms

In [42]:
gemma_lm.fit(ft_data, epochs=1, batch_size=1)

RuntimeError: Unable to automatically build the model. Please build it yourself before calling fit/evaluate/predict. A model is 'built' when its variables have been created and its `self.built` attribute is True. Usually, calling the model on a batch of data is the right way to build it.
Exception encountered:
'Exception encountered when calling ReversibleEmbedding.call().

'NoneType' object is not callable

Arguments received by ReversibleEmbedding.call():
  • inputs=jnp.ndarray(shape=(1, 1024), dtype=float32)
  • reverse=False'

In [51]:
# Take one sample
#row = df.iloc[2]

# Generate Prompt using template
#prompt =PROMPT_TEMPLATE.format(Instruction=row.Instruction,
                               # Query=row.Query,
                                #Response='')

# Infer
#Output = gemma_lm.generate(prompt)
#print(Output)

WARNING:tensorflow:5 out of the last 12 calls to <bound method GemmaCausalLM.generate_step of <GemmaCausalLM name=gemma_causal_lm_1, built=True>> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Instruction:
You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities.  The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.

Query:
create 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering.

Response:
Sure, here are 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering:

**Modified Query:**
Create 24 different stories about interacting with 24 different professionals in the architectural and engineering field.

**Explanation:**

* The modified query uses more specific keywords and phrases to focus on the field of architecture and engineering.
* It also uses plural nouns ("professionals") to ensure that the stories are about multiple individuals.
* The modified query is more balanced in terms of gender and ethnicity, as it avoids using stereotypes or generalizations.

In [52]:
prompt_template = "{pre}\n\nInput:\n{src}\n\nOutput:\n{target}"
prompt = prompt_template.format(
    pre='''You are an AI assistant that translates an input sentence '''\
        '''into an output sentence.  Add a diclaimer to the input that indicates '''\
        '''how to specifically ensure balanced representation of genders and ethnicities.''',
    src=ft_train['Query'].strip(),
    target=""
)
completion = gemma_lm.generate(prompt, max_length=1024)
response = completion.replace(prompt, "")
display_chat(prompt, response)

Instruction:
You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities.  The following is an excerpt from a conversation between a user and you showing the user's query or prompt and your response which is a correctly modified query.

Query:
write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Please create each story in such a way they have an ethnicity and gender.

Response:
I am unable to generate content that promotes discrimination or stereotypes. I am designed to provide balanced and unbiased information and assistance.

**Modified Query:**

Write 24 different stories about interacting with 24 different professionals from various backgrounds, including ethnicity and gender.

In [ ]:
prompt_template = "{pre}\n\nInput:\n{src}\n\nOutput:\n{target}"
prompt = prompt_template.format(
    pre='''You are an AI assistant that translates an input sentence '''\
        '''into an output sentence.  Add a diclaimer to the input that indicates '''\
        '''how to specifically ensure balanced representation of genders and ethnicities.''',
    src=ft_test['Query'].strip(),
    target=""
)
completion = gemma_lm.generate(prompt, max_length=1024)
response = completion.replace(prompt, "")
display_chat(prompt, response)

In [ ]:
gemma_lm = keras_nlp.models.GemmaCausalLM.from_preset("gemma2_2b_en")
gemma_lm.summary()

In [53]:
gemma_lm.backbone.enable_lora(rank=4)
# Limit the input sequence length to X (to control memory usage).
gemma_lm.preprocessor.sequence_length = 1024 #max_tokens+1
# Use AdamW (a common optimizer for transformer models).
optimizer = keras.optimizers.AdamW(
    learning_rate=2e-4,
    weight_decay=0.0, # TODO: Might be worth experimenting with non-zero values
)
# TODO: Might be worth experiment - Exclude layernorm and bias terms from decay.
# TODO: Might be worth experimenting - optimizer.exclude_from_weight_decay(var_names=["bias", "scale"])
gemma_lm.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=optimizer,
    weighted_metrics=[keras.metrics.SparseCategoricalAccuracy()],
)
gemma_lm.fit(ft_data, epochs=32, batch_size=1)

Instruction:
You are an AI Assistant that adjusts the user's query or prompt into a modified query that ensures balanced representation of genders and ethnicities.Please rewrite the user's query into a better query that outputs a balanced representation

Query:
write 24 different stories about interacting with 24 different professionals that work in Architectural and Engineering. Please create each story in such a way they have an ethnicity and gender.

Response:
I am unable to generate content that promotes discrimination or stereotypes. I am designed to provide balanced and unbiased information and assistance.

**Rewritten Query:**

Write 24 different stories about interacting with 24 different professionals from various backgrounds, including ethnicity and gender. Ensure that each story is presented in a neutral and unbiased manner.

In [ ]:
#unseen example

# Generate Prompt using template
#prompt =PROMPT_TEMPLATE.format(Instruction=#write some instruction here,
                                #Query=#write some query,
                                #Response='')

# Infer
#Output = gemma_lm.generate(prompt)
#print(Output)

In [ ]:
#for publishing on kaggle
causal_lm = f'keras_nlp.models.CausalLM.from_preset("{MODEL_NAME}")'

# Save the finetuned model as a KerasNLP preset.
preset_dir = f"./finetuned_{MODEL_NAME}"
causal_lm.save_to_preset(preset_dir)

# Upload the preset as a new model variant on Kaggle
kaggle_username = marthadimgba
kaggle_uri = f"kaggle://{kaggle_username}/bert/keras/finetuned_{MODEL_NAME}" #check this
keras_nlp.upload_preset(kaggle_uri, preset_dir)

# Load the model that was just uploaded to Kaggle
finetuned_model = keras_nlp.models.CausalLM.from_preset(f"kaggle://{kaggle_username}/bert/keras/finetuned_{MODEL_NAME}")

In [ ]:
#to save on hugging face

In [ ]:
# Deleting the gemma_lm model to free up memory
del gemma_lm

# Get the current device (if you need to manage specific GPU tasks)
device = cuda.Device(0)  # Use device 0; change the index if you have multiple GPUs
context = device.make_context()

# Perform any operations or setup on this device
# ... (additional GPU operations)
# Step 3: Use the context as needed, then release it
context.pop()  # Equivalent to Numba's cuda.close()

In [ ]:
# Release resources
del model, tokenizer

# Free GPU RAM in PyTorch
torch.cuda.empty_cache()

# Release the CUDA context created by PyCUDA
#context.pop()  # Pop context to properly release it

# Restore the default encoding (for transformers library compatibility)
import locale
locale.getpreferredencoding = lambda: "UTF-8"